#!/bin/bash
# Date : 2015-11-09
# Last revision : 2018-04-14
# Wine version used : 2.16-staging
# Distribution used to test : Ubuntu, Mint, Xubuntu
# Author : Hoek
# Email : hoek@tuta.io
# Licence : GPLv3
# PlayOnLinux:  playonlinux-4.2.10
# Always up to date: https://github.com/h0ek/POL_EntropiaUniverse
     
[ "$PLAYONLINUX" = "" ] && exit
source "$PLAYONLINUX/lib/sources"

WINEVERSION="2.16-staging"

TITLE="Entropia Universe"
AUTHOR="Hoek"
PUBLISHER="Mindark PE AB"
PREFIX="EntropiaUniverse"
GAME_URL="http://www.entropiauniverse.com/"
     
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
     
POL_SetupWindow_Init
POL_SetupWindow_SetID 2258
POL_Debug_Init
POL_SetupWindow_presentation "$TITLE" "$PUBLISHER" "$GAME_URL" "$AUTHOR" "$PREFIX"
POL_System_TmpCreate "$PREFIX"
     
POL_SetupWindow_InstallMethod "LOCAL,DOWNLOAD"
     
if [ "$INSTALL_METHOD" = "LOCAL" ]
then
	POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run')" "$TITLE"
	INSTALLER="$APP_ANSWER"
elif [ "$INSTALL_METHOD" = "DOWNLOAD" ]
then
	cd "$POL_System_TmpDir"
	POL_Download "http://install2.entropiauniverse.com/entropia_universe_setup.exe" "582E0934F8B45BE40C017506F87F722C"
	INSTALLER="$POL_System_TmpDir/entropia_universe_setup.exe"
fi
     
POL_System_SetArch "x86"
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WINEVERSION"
     
POL_Call "POL_Install_corefonts"
POL_Call "POL_Install_vcrun2012"
POL_Call "POL_Install_d3dx9"
     
POL_Wine_WaitBefore "$TITLE"
POL_Wine "$INSTALLER"
     
POL_System_TmpDelete
     
Set_OS "win7"
POL_Wine_X11Drv "GrabFullScreen" "Y"
POL_Wine_X11Drv "Managed" "Y"
POL_Wine_X11Drv "Decorated" "Y"
POL_Wine_UpdateRegistryWinePair 'DllRedirects' 'wined3d' 'wined3d-csmt.dll'
POL_Shortcut "ClientLoader.exe" "$TITLE"
     
POL_SetupWindow_Close
exit
